#neutron_customer_services:
#    resource: "@NeutronCustomerServicesBundle/Resources/config/routing.xml"
#    prefix:   /

#neutron_social_networks:
#    resource: "@NeutronSocialNetworksBundle/Resources/config/routing.xml"
#    prefix:   /admin/widget/social-networks

neutron_block_text:
    resource: "@NeutronBlockTextBundle/Resources/config/routing.xml"
    prefix:   /admin/widget/block-text


NeutronSeoBundle:
    resource: "@NeutronSeoBundle/Resources/config/routing.xml"
    prefix:   /


NeutronTreeBundle:
    resource: "@NeutronTreeBundle/Resources/config/routing.xml"
    prefix:   /

NeutronComponentBundle:
    resource: "@NeutronComponentBundle/Resources/config/routing.xml"
    prefix:   /

NeutronAdminBundle:
    resource: "@NeutronAdminBundle/Resources/config/routing.xml"
    prefix:   /admin

NeutronUserBundle:
    resource: "@NeutronUserBundle/Resources/config/routing.xml"
    prefix:   /admin

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    
    
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /admin/profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /admin/resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /admin/profile
    
fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /admin/group
    
DataGridBundle:
    resource: "@NeutronDataGridBundle/Resources/config/routing.yml"
    prefix:   /  

NeutronFormBundle:
    resource: "@NeutronFormBundle/Resources/config/routing.yml"
    prefix:   /
    
JMSTranslationBundle_ui:
    resource: @JMSTranslationBundle/Controller/
    type:     annotation
    prefix:   /admin/translation
    
_imagine:
    resource: .
    type:     imagine
   
NeutronPageBundle:
    resource: "@NeutronPageBundle/Resources/config/routing.xml"
    prefix:   /
     
AppBundle:
    resource: "@AppBundle/Resources/config/routing.xml"
    prefix:   /
       
NeutronLayoutBundle:     
    resource: .
    type: extra
 
# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
